redis:
  address: "localhost:6379"

postgres:
  host: "localhost"
  port: "5432"
  user: "books_psql"
  password: "books_psql_pass"
  database: "books_psql"
  sslMode: "disable"

pool:
  workerCount: 6

benchmark:
  runs: 10
  tests: 1
