version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
  redis_db:
    image: redis:latest
    container_name: redis_db
    ports:
      - '6379:6379'
